### ISSUE TITLE
Primera edición

### ISSUE THREAD

**Issue by jessica123c** [esteban2oo1/software_Des#11]
## software para tapiceria

Se hará un software de registro, inventarios, ventas y prestamos para los clientes que sistematice la empresa.

## tendremos los siguientes pasos principales para desarrollar el sotware

1. Obtener toda la información de la empresa y como trabaja actualmente
2. diligenciar tareas entre todo el grupo para agilizar el trabajo
3. Desarrollar cada tarea diligenciada

## Comportamiento Esperado
[Describe lo que esperabas que sucediera.]

## Comportamiento Actual
[Describe lo que realmente está sucediendo.]

## Capturas de Pantalla
[Si es relevante, adjunta capturas de pantalla o imágenes que muestren el problema.]

## Información Adicional
[Agrega cualquier información adicional que creas que sea relevante para comprender o solucionar el problema, como versiones de software, enlaces o contexto.]

## Ambiente
- **Sistema Operativo:** [ejemplo: Windows 10]
- **Navegador (si aplica):** [ejemplo: Google Chrome 90.0.4430.85]
- **Versión de la Aplicación (si aplica):** [ejemplo: MiApp v1.2.3]

## Pasos para Reproducir (opcional)
[Si el problema es complejo o necesita una configuración especial, proporciona un conjunto detallado de pasos para reproducirlo.]

1. Paso 1:
   - Subpaso A
   - Subpaso B
2. Paso 2:
3. Paso 3:

## Notas Adicionales (opcional)
[Agrega cualquier nota o comentario adicional que consideres relevante.]

## Etiquetas (opcional)
[Etiquetas relevantes para categorizar este issue, como "bug," "mejora," "documentación," etc.]

## Tareas Asignadas (opcional)
- [ ] Tarea A
- [ ] Tarea B

**Nota:** Por favor, asegúrate de seguir estas pautas y proporcionar información detallada para que podamos investigar y solucionar el problema de manera efectiva.

**Comment by esteban2oo1** [comment]
bien pelao
